version: "3.7"
services:
  mongodb:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-books_database}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - ./db/mongo:/data/db

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - mongodb

  ndse_counter:
    build: ./ndse-counter
    expose:
      - 80
    ports:
      - 80:80
    environment:
      - PORT=80

  ndse_library:
    build: ./ndse-library
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - COUNTER_URL=ndse_counter
      - DB_URL=mongodb://${DB_USERNAME:-root}:${DB_PASSWORD:-password}@mongodb:27017/
      - COOKIE_SECRET=${COOKIE_SECRET:-COOKIE_SECRET}
    depends_on:
      - mongodb
      - ndse_counter
    links:
      - ndse_counter
      - mongodb
